version: '3.9'

services:
  app:
    image: boogiedk/swipe-vibe-app:latest
    build:
      context: .
      dockerfile: ./SwipeVibe.Backend/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=swipe-vibe-app;Password=swipe-vibe-app;Database=swipe-vibe-db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: swipe-vibe-app
      POSTGRES_PASSWORD: swipe-vibe-app
      POSTGRES_DB: swipe-vibe-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
