name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push swipe-vibe-app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./SwipeVibe.Backend/Dockerfile
          push: true
          tags: boogiedk/swipe-vibe-app:latest

      - name: Deploy to VPS
        run: |
          sudo apt-get install -y expect
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          echo "${{ secrets.VPS_PRIVATE_KEY_PASSPHRASE }}" | expect -c "spawn ssh-add private_key; expect \"Enter passphrase:\"; send -- \"${{ secrets.VPS_PRIVATE_KEY_PASSPHRASE }}\r\"; expect eof"
          rm -f private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "mkdir -p /home/${{ secrets.VPS_USERNAME }}/project"
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USERNAME }}/project
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r * ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USERNAME }}/project
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} <<-EOF
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker-compose -f /home/${{ secrets.VPS_USERNAME }}/project/docker-compose.yml down --volumes || true
          docker-compose -f /home/${{ secrets.VPS_USERNAME }}/project/docker-compose.yml pull
          docker-compose -f /home/${{ secrets.VPS_USERNAME }}/project/docker-compose.yml up -d --force-recreate
          EOF

